apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: fpm1
  name: fpm1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fpm1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/teachersselector-internal: "true"
        io.kompose.service: fpm1
    spec:
      containers:
        - image: balance/php
          name: fpm1
          resources: {}
          volumeMounts:
            - mountPath: /var/www/app
              name: fpm1-claim0
      restartPolicy: Always
      volumes:
        - name: fpm1-claim0
          persistentVolumeClaim:
            claimName: fpm1-claim0
status: {}
