apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: pgsql
  name: pgsql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/teachersselector-internal: "true"
        io.kompose.service: pgsql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: pgsql
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -d
                - ""
                - -U
                - ""
            failureThreshold: 5
            timeoutSeconds: 5
          name: pgsql
          ports:
            - containerPort: 5432
              hostPort: 5496
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgsql-data
      restartPolicy: Always
      volumes:
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: pgsql-data
status: {}
