#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

teachers:
    path: /teachers
    controller: App\Infrastructure\Http\Teacher\Controller\CreateTeacherController::createTeacher

new_message:
    path: /new_message
    controller: App\Infrastructure\Http\Teacher\Controller\CreateTeacherController::newMessage