name: BuildAndDeploy

on: [push]

#TODO немного допилить, добавить зависимости и диагностику на стадии github
#TODO доступы все убрать в секреты!

jobs:
  deploy_to_remote_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Transfer files
#        uses: appleboy/scp-action@master
#        with:
#          host: 195.133.146.184
#          username: root
#          password: VNahVcL9e7
#          port: 22
#          source: "./docker-compose.yaml,./.env,./docker/**"
#          target: "~/myapp"

      - name: Update and rebuild project on the production server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: root
          password: VNahVcL9e7
          port: 22
          script: |
            cd ~/TeachersSelector
            echo "📥 Pulling latest code..."
            git pull
      
            echo "🐳 Restarting Docker..."
            docker compose up -d --build
      
            echo "📦 Installing Composer dependencies..."
            docker exec -w /var/www/app fpm1 composer install --no-interaction --prefer-dist
      
            echo "⚙️ Updating database schema..."
            docker exec -w /var/www/app fpm1 php bin/console doctrine:schema:update --force
      
            echo "📚 Loading fixtures..."
            docker exec -w /var/www/app fpm1 php bin/console doctrine:fixtures:load --no-interaction
      
            echo "🧪 Running PHPUnit tests..."
            docker exec -w /var/www/app fpm1 php bin/phpunit --testdox --colors=always