name: Build and Push Docker Compose Images

on:
  push:

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/nginx/Nginx.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/balance-nginx:latest

      - name: Build and Push PHP (FPM)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/php/Fpm.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/balance-php:latest

      - name: Build and Push PostgreSQL
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/db/Db.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/balance-db:latest