name: BuildAndDeploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker containers
        run: docker compose up -d --build

      - name: Fix permissions
        run: docker exec -d fpm1 chown -R www-data:www-data /var/www/app/var

      - name: Install dependencies
        run: docker exec fpm1 composer install

      # 2. Скачиваем wait-for-it.sh
      - name: Download wait-for-it.sh
        run: curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh

      - name: Make wait-for-it.sh executable
        run: chmod +x wait-for-it.sh

      # 4. Копируем скрипт ожидания в контейнер
      - name: Copy wait-for-it.sh into fpm1
        run: docker cp wait-for-it.sh fpm1:/wait-for-it.sh && docker exec fpm1 chmod +x /wait-for-it.sh

      # 6. Создаём базу
      - name: Create database
        run: docker exec -w /var/www/app fpm1 php bin/console doctrine:database:create --if-not-exists

      # 7. Запускаем миграции
      - name: Run migrations
        run: docker exec -w /var/www/app fpm1 php bin/console doctrine:migrations:migrate --no-interaction



#      - name: Sleep before DB init
#        run: sleep 15
#
#      - name: Creating database
#        run: docker exec fpm1 php bin/console doctrine:database:create

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to GHCR
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

#      - name: Build and Push nginx
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./docker/nginx/Nginx.Dockerfile
#          push: true
#          tags: ghcr.io/${{ github.repository_owner }}/balance-nginx:latest
#
#      - name: Build and Push PHP (FPM)
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./docker/php/Fpm.Dockerfile
#          push: true
#          tags: |
#            ghcr.io/${{ github.repository_owner }}/balance-php:latest
#
#      - name: Build and Push PostgreSQL
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./docker/db/Db.Dockerfile
#          push: true
#          tags: ghcr.io/${{ github.repository_owner }}/balance-db:latest


#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: List files
#        run: ls -la
#
#      - name: Transfer files
#        uses: appleboy/scp-action@master
#        with:
#          host: 195.133.146.184
#          username: root
#          password: VNahVcL9e7
#          port: 22
#          source: "./docker-compose.yaml,./.env,./docker/**"
#          target: "~/myapp"
#
#      - name: Deploy to docker compose
#        uses: appleboy/ssh-action@v1.2.0
#        with:
#          host: 195.133.146.184
#          username: root
#          password: VNahVcL9e7
#          port: 22
#          script: |
#            cd ~/myapp
#            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PERSONAL_GITHUB_TOKEN }}
#            docker compose -f docker-compose.yaml pull
#            docker compose -f docker-compose.yaml up --build